@contentType = multipart/form-data;

### 01. Admin Login

POST {{$dotenv ROOT_DIR}}/api/admin/login.php 
Content-Type: {{contentType}} boundary=----admin-login

------admin-login
Content-Disposition: form-data; name="username"

admin
------admin-login
Content-Disposition: form-data; name="password"

123456
------admin-login--

### 02. Read Categories

POST {{$dotenv ROOT_DIR}}/api/shared/read-categories.php 
Content-Type: {{contentType}} boundary=----read-categories

------read-categories
